### ISSUE TITLE
Color of bullet navigation

### ISSUE THREAD

**Issue by holzru** [xiaolin/react-image-gallery#110]
Can the feature of being able to color the bullets that display where you are and allow click navigation be added or does it exist, in which case can it be pushed to public readme. It just suffers when the pictures have a white background.

**Comment by holzru** [comment]
Side note you have to use the !important tag, because life

**Comment by xiaolin** [comment]
You don't need !important if you are specific enough. The below snippet should work as long as its declared after the initial declaration of the class.

```scss
.image-gallery-bullets .image-gallery-bullet {
  &.active {
    background: $your-own-color;
  }
}
```
