### ISSUE TITLE
set max height for gallery container

### ISSUE THREAD

**Issue by abonec** [xiaolin/react-image-gallery#162]
I have many photos and they are in different orientations (some are in horizontal and some are in vertical) in different gallery sets (all photos in gallery almost always has a horizontal or a vertical orientation). Wide images is almost look fine with default settings but tall images look awful
![image](https://cloud.githubusercontent.com/assets/240587/23749809/12f6e854-04db-11e7-80a0-2448f400b264.png)
I can't understand how to set max-height for gallery container.
`.image-gallery {max-height: 400px}` do nothing at all.

If I set `.image-gallery {width: 500px}` it will affect to fullscreen mode and made it useless and width property affecting wide photos which become very tiny.

**Comment by xiaolin** [comment]
you need to set the height on the image itself so it should be
```
.image-gallery-image img {
 max-height: 400px;
}
```

**Comment by abonec** [comment]
And how to cancel this in fullscreen? If I set `max-height: none` very tall image are not fit in screen and thumbnails is out of a screen.

**Comment by xiaolin** [comment]
There is a `fullscreen` class added to the gallery once its in full screen mode if you need different css for fullscreen and non fullscreen. Since this is a CSS question and unrelated to the library I'm closing this.

**Comment by abonec** [comment]
Can you add something like 'non-fullscreen' class to stylish only standard view?

**Comment by xiaolin** [comment]
You shouldn't need that. You can nest css classes.

```
.image-gallery {
  // regular css.
  width: 400px;
}

.image-gallery.fullscreen {
  // your full screen css
  width: 600px;
}

**Comment by abonec** [comment]
I know that, but I set property to `.image-gallery` and should cancel it in `.image-gallery.fullscreen` instead of just set in once in `.image-gallery.non-fullscreen`

**Comment by xiaolin** [comment]
ah, that should be easy enough to add, if you like open a PR, and I can merge it.

**Comment by ivarne** [comment]
I think i solved a similar problem with

```css
.image-gallery-content:not(.fullscreen) .image-gallery-image {
  width: 100%;
  height: 0;
  padding-top: 75%; /* Make the image wrapping div take a ratio of 3:4 */
  position: relative;
  img {
    position: absolute;
    top: 0;
    object-fit: cover;
    object-position: center center;
    width: 100%;
    height: 100%;
  }
}
```
