### ISSUE TITLE
Custom animation on slide (image transitions) apart from slide

### ISSUE THREAD

**Issue by solancer** [xiaolin/react-image-gallery#166]
I'm trying to add 3 different types of animation for the image slide animation.

In the source I see that your setting a transition style can this be modified to achieve fade, zoom or any other animation transition on image slide?

```
   this.setState({
      previousIndex: currentIndex,
      currentIndex: nextIndex,
      offsetPercentage: 0,
      style: {
        transition: `transform ${this.props.slideDuration}ms fade-in`
      }
    });
```

**Comment by jordanoverbye** [comment]
+1

**Comment by xiaolin** [comment]
@solancer There is no such transition property called `fade-in` but I've adjusted the transition property to be applied to all transitions in v0.7.15

```javascript
   this.setState({
      previousIndex: currentIndex,
      currentIndex: nextIndex,
      offsetPercentage: 0,
      style: {
        transition: `all ${this.props.slideDuration}ms fade-in`
      }
    });
```

This way you can override the css classes and all transitions will take affect.

e.g.
overriding the following css will allow you to add the fade affect

```css
.image-gallery-slide {
  opacity: 0;
}
.image-gallery-slide.center {
 opacity: 1;
}
```

**Comment by nishtacular** [comment]
@xiaolin @solancer I tried adding the above css however, the image still slides in, i can see the image sliding out fading out. How can I replace the slide with the fade action. Appreciate any pointers.

**Comment by xiaolin** [comment]
@nishtacular you can adjust the transition to only transition on opacity removing the transform transition.
```
.image-gallery-slide {
  opacity: 0;
  transition: opacity 450ms ease-out !important;
}
```
This will remove the slide effect.

**Comment by solancer** [comment]
@xiaolin I've been experimenting with GASP and React and it seems to work flawlessly. By porting react-image-gallery's animation bit to GASP can make things very easy and extensible.

The main issue with the current setup is that css transitions cannot be combined and css keyframes animations are sh**t because it can't be declared and applied to an element on the fly. Even Reactjs -animations & Radium can't help.

The best way to go about is to use GASP TweenMax lib to add support for all kinds of animation.

It's no surprise that many gallery gallery plugins out there don't have support for more than 2-3 types of animations.

**Comment by xiaolin** [comment]
GSAP looks pretty cool, I'll take a look into adding more animations to the library when I get a chance.

**Comment by xiaolin** [comment]
@solancer I'm curious what kinda issues you're having with keyframes? I was able to add keyframes using css and got some simple animations going

![3lyt6r](https://user-images.githubusercontent.com/1286776/29903528-53398982-8dd2-11e7-8d2e-ccd3c52bf3d9.gif)


```css
@keyframes blinker {
  from { opacity: 1; }
  to { opacity: .3; }
}
@keyframes spinner-rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
.image-gallery-slide.center {
    animation: spinner-rotate .4s cubic-bezier(.5, 0, 1, 1), blinker .4s cubic-bezier(.5, 0, 1, 1);
}
```

**Comment by solancer** [comment]
the project I'm working is a bit more complex, can't have classes or id selectors, only inline styling on refs. The problem with keyframes is that it needs to be applied onto an element to work. GASP is the only thing that helped me do what I had intended.

![screen shot 2017-08-31 at 8 10 07 am](https://user-images.githubusercontent.com/800668/29903918-fd0a26d2-8e23-11e7-87a1-0342dc7a4b33.png)

**Comment by xiaolin** [comment]
Gotcha, cool. Glad you got it working!

**Comment by dmt0** [comment]
To get fade animation to work in the current version, CSS had to be slightly different from what's above:

```css
.image-gallery-center {
  opacity: 1 !important;
}
.image-gallery-slide {
  opacity: 0;
  transition: opacity 450ms ease-out !important;
}
```
