### ISSUE TITLE
About full screen thumbnails and navigation

### ISSUE THREAD

**Issue by qwe75300** [xiaolin/react-image-gallery#241]
Hello Xiaolin
This image gallery is Great, thank you

How to hide thumbnails and navigation, and then display them in full screen?
showNav and showThumbnails changed to false, including the full screen will be hidden, but I want that the full screen is displayed

**Comment by xiaolin** [comment]
There is a `fullscreen` class added to the gallery when its in fullscreen.
You could use css to hide/display the navigation and thumbnail as an option.

(not tested)
```css
.image-gallery-left-nav {
 display: none;
}
.image-gallery .fullscreen .image-gallery-left-nav {
  display: block;
}
```
