### ISSUE TITLE
left and right-nav how to change the blue border color that appears on click?

### ISSUE THREAD

**Issue by Stathismi** [xiaolin/react-image-gallery#366]

**Comment by xiaolin** [comment]
Closing

**Comment by dunklesToast** [comment]
For newer Versions it needs to be
```css
.image-gallery-right-nav:hover::before, .image-gallery-left-nav:hover::before {
    color: pink;
}
```
