### ISSUE TITLE
image inline styling

### ISSUE THREAD

**Issue by Vahe83** [xiaolin/react-image-gallery#392]
Hi Xiaolin,

Could you show example how can I add inline styling(transform: rotate(90deg)) to the images in the slider?

Thank you in advance.

**Comment by xiaolin** [comment]
You can override the css
```css
.image-gallery-slide img {
    transform: rotate(90deg);
}
```
