### ISSUE TITLE
Fullscreen button goes away on large screens when full screen is activated

### ISSUE THREAD

**Issue by BjoernRave** [xiaolin/react-image-gallery#439]
Hey, first up I really like your library. 

Just one thing which I would like is to be able to exit the fullscreen by clicking the fullscreen button a second time

**Comment by xiaolin** [comment]
The fullscreen button is still available, you can click again to close it.

**Comment by BjoernRave** [comment]
really doesnt work for me, but I will check again

**Comment by djorg83** [comment]
For me the image is larger than the screen, and its forcing the fullscreen close button out of the viewable area.  The page is not scrollable, so I cannot get to the button.

**Comment by djorg83** [comment]
I solved it with the following css rule.

``` css
.image-gallery-slide img {
    width: 100vw;
    max-height: 100vh;
}
```

**Comment by xiaolin** [comment]
That will stretch your image and it won't maintain aspect ratio. I suggest keeping width auto and prioritize based on height during fullscreen.

something like

```scss
.image-gallery-content.fullscreen  {
  .image-gallery-slide img {
    width: auto;
    max-height: 100vh;
  }

  .image-gallery-image {
    text-align: center;
  }
}
```

I'll mark this as a bug as full-screen shouldn't extend past the height of the entire screen.
