### ISSUE TITLE
Image height affects component height

### ISSUE THREAD

**Issue by tonyjmnz** [xiaolin/react-image-gallery#48]
My images have different sizes and when I'm scrolling through them, the height of the component changes. Is there a way to make the image viewport of a static height?

**Comment by xiaolin** [comment]
If you want a static height you can add the extra css below to override the included css

```css
.image-gallery-slides {
  text-align: center;
}

.image-gallery-slide {
  background: #fff;
  img {
    width: auto;
    height: 400px;
  }
}
```

Note, by setting a static height you remove the ability for the gallery to be fully responsive.
If you can resize all your images to a fixed width/height that would be ideal.
