### ISSUE TITLE
Off-center description box? How to change it?

### ISSUE THREAD

**Issue by lenghuang** [xiaolin/react-image-gallery#497]
Hello,
I was wondering if there was anyone I could overwrite the description styling to center the description box? For some other things, like thumbnail labels, I've be able to do things like adding my own css declaration for .image-gallery-thumbnails { stylestuff } in my App.css. However, I have not been able to do the same with the description box. All I want to do is somehow center it.
Thank you!
![Screen Shot 2020-03-26 at 9 13 29 PM](https://user-images.githubusercontent.com/32604574/77711419-58e75a80-6fa7-11ea-934d-6a0af8b39d2a.png)

**Comment by xiaolin** [comment]
You can override the style for description box using `.image-gallery-description`
something like

```css
.image-gallery-description {
  right: 0px;
  left: 0;
  margin: 0 auto;
  widdth: 200px;
}
```
