### ISSUE TITLE
I want to disable RTL & LTR Moment of Images

### ISSUE THREAD

**Issue by Sambasivaraonagidi** [xiaolin/react-image-gallery#509]
HI We need slider without   RTL & LTR Moment  How can we do that

**Comment by xiaolin** [comment]
You can modify the css to transition differently. 

The below css will make it so the images fade in and out instead of sliding.

```css
.image-gallery-slide {
  opacity: 0;
  transform: none !important;
}

}
.image-gallery-slide.center {
  opacity: 1;
}
```

You can also adjust how long the animation should last by adjusting the prop `slideDuration`
