### ISSUE TITLE
Full screen = gallery in the middle of screen

### ISSUE THREAD

**Issue by a-tonchev** [xiaolin/react-image-gallery#527]
Is it possible to place gallery in the middle of the screen when it is full screen? Right now gallery is on the top of the screen

If not that would be a nice feature.

**Comment by xiaolin** [comment]
Can you share a screenshot? It should be vertically centered in fullscreen mode.

**Comment by alexfiftysix** [comment]
I'm seeing the same issue when on small screens. 
Getting this on iPhone XR and with iPhone X screen size in Google Chrome

![image](https://user-images.githubusercontent.com/25026852/88632904-9dbb0380-d0f7-11ea-8d3e-afbffad87337.png)

**Comment by xiaolin** [comment]
On mobile it uses the CSS below to center aligned because there is no fullscreen API support. On desktop that CSS is not applied because its using the fullscreen API. 
```css
  &.fullscreen-modal {
    background: $ig-black;
    bottom: 0;
    height: 100%;
    left: 0;
    position: fixed;
    right: 0;
    top: 0;
    width: 100%;
    z-index: 5;

    .image-gallery-content {
      top: 50%;
      transform: translateY(-50%);
    }
  }
```
