### ISSUE TITLE
Responsive Image Size

### ISSUE THREAD

**Issue by SamKomesarook** [xiaolin/react-image-gallery#745]
**Is your feature request related to a problem? Please describe.**
Thanks so much for the component! It would be great to have the option for a responsive image size (without srcSets) that sets the image to be contained within the parent.

**Describe the solution you'd like**
Perhaps a boolean prop that sets the image to 100% height and width of the parent, with the object-fit set to contain.

**Describe alternatives you've considered**
This styling could be applied via custom styles or classes to the image.

**Comment by xiaolin** [comment]
If you're planning to use images with varying heights/widths. You can solve this using CSS.

**Comment by dmt0** [comment]
Something like this worked for me:

```scss
.image-gallery-slides {
  max-height: $imageHeight !important;
  .image-gallery-image {
    max-height: $imageHeight !important;
    max-width: 100%;
    object-fit: contain;
    width: 100%;
    height: 100%;
  }
}
```
You may not need all of this, but the key is to size `image-gallery-slides` and `image-gallery-image`
