### ISSUE TITLE
Setting gallery height without impact on fullscreen mode

### ISSUE THREAD

**Issue by boly38** [xiaolin/react-image-gallery#774]
**Is your feature request related to a problem? Please describe.**
First thanks for this amazing project !
second I'm not sure my request is exaclty the same as #745

What I'm trying to do is a "with-fixed-height" gallery component where gallery images array entries (jpg image) have different raw height. 

So I want the gallery to always have the same height and this without link to the current showed image.

**Describe the solution you'd like**
I would like one of theses : 
- a `galleryHeight` attribute that dont apply in full-screen mode
- or updating existing `originalHeight` attribute that apply only on gallery view and not on fullscreen mode
- or the component adds an extra css in full-screen mode that end-user could customize..

**Describe alternatives you've considered**

A) I'm able to fix the image height by setting `originalHeight` attribute on images entries and that's cool. 
⚠️ But the bad news is that this attributes also apply to the fullscreen mode.So this is no more a "fullscreen mode"

B) I've the same result by overriding following css; example: 
````css
.image-gallery-slide .image-gallery-image {
    max-height: 300px !important;
}
````

NB: I noticed the presence of `:not(:root):fullscreen` in calculated css, but `:fullscreen` [seems](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen) compatible with firefox only (I'm using google chrome and need to be compatible with mainstrream browsers)

C) I've tried to put the gallery in a parent `div` having fixed height, but the gallery dont respect this height limitation.

D) I've also tried `useBrowserFullscreen={false}` but without success

In fact today I've no alternative. I've the choice to have a fixed height everywhere (that put useless fullscreen mode)
or else I keep gallery without  `originalHeight` attribute  and my component height is not always the same. That look not well depends on the image height...

**Additional context**
I'm not super-man-in-css so that is possible I'm missing something to do with css or maybe with "html 5 sizes" attribute.
any hint appreciated.

**Comment by xiaolin** [comment]
a `fullscreen` class is added to the `image-gallery-content` when in fullscreen, so the below should get you what you need.

```css
.image-gallery-content:not(.fullscreen) .image-gallery-slide .image-gallery-image {
    max-height: 300px; 
}
```

**Comment by boly38** [comment]
Hey

thank you for your quick and efficient response 🙏 

This works like a charm  🥇  !

````css
.image-gallery-content:not(.fullscreen) .image-gallery-slide:not(.fullscreen) .image-gallery-image:not(.fullscreen) {
    max-height: 300px;
}
````

From my point of view, and if it is not useful to add this element to the doc(?), this ticket can be closed.

Best regards 👍
