### ISSUE TITLE
More control over icons

### ISSUE THREAD

**Issue by ilxanlar** [xiaolin/react-image-gallery#98]
I wonder if I could have more control over icons, I mean some props for icons. Right now the only way to handle the icons is CSS.
We can do something like this:

```
<ImageGallery
  ...
  iconNext={<i className="fa-angle-right"/>}
  iconPrev={<i className="fa-angle-left"/>}
  iconFullscreen={<i className="fa-extend"/>}
  iconPlay={<i className="fa-play"/>}
/>
```

**Comment by xiaolin** [comment]
You have full control to override the icon using css? Is there a reason you want to use markup language vs css pseudo elements?

**Comment by ilxanlar** [comment]
I'm using your package, and I'm really grateful! Thank you!

I use `grunt-webfont` to build my icons in my project. Every time `grunt-webfont` rebuilds the icons, it sets characters randomly or _whatever-ly_. I can handle this problem with `codepoints` but if I had access to icons markup, it would be a lot lot easier.

Another reason for me is I think it's not clean this way:
```
.image-gallery-left-nav:before {
  content: "\f105";
  font-family: "SomeFontName";
}
```

For example I use separate component for icons in my project, `<Icon name="next"/>`, wouldn't that be so clear and clean to use it this way, without any CSS?
```
<ImageGallery
  nextIcon={<Icon name="next"/>}
  prevIcon={<Icon name="prev"/>}
  ...
/>
```

**Comment by xiaolin** [comment]
@ilxanlar probably a debatable topic haha lots of people like using pseudo elements as icons. 

e.g.
```scss
@mixin ionicon($value) {
  font-family: $some-icon-font-family;

  &::before {
    content: $value;
  }
}

.image-gallery-left-nav {
   @include ionicon($next);
}

.image-gallery-left-nav {
   @include ionicon($prev);
}
```

This way I don't need to add extra markup for icons. `<i class='prev'></i>` etc...

What is your use case for having an `Icon` component?

**Comment by ilxanlar** [comment]
@xiaolin I do not say that you remove this pseudo thing, I'm saying that let me modify these elements. May be only an icon isn't enough.
By the way, does it not feel good to use a component for icons, `Icon`? :D

**Comment by xiaolin** [comment]
Right now I don't have any markup for icons that will make it easy to replace and insert custom icons.

```jsx
<a
  className={`image-gallery-fullscreen-button${isFullscreen ? ' active' : ''}`}
  onClick={this._toggleFullScreen.bind(this)}/>
```

Icons like `fullscreen`, and `play` are also toggled  which adds more complexity.

Instead override the css with your own icon library.

e.g.

```scss

%custom-icon {
  font-family: $your-own-icon-faily;
}


.image-gallery-fullscreen-button {

  &::before {
   @extend %custom-icon;
    content: $your-fullscreen-icon;
  }

  &.active::before {
    content: $your-off-fullscreen-icon;;
  }

}
```
